"""
Django settings for stunotes project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from decouple import config

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: read secret key and debug mode from environment
SECRET_KEY = config('SECRET_KEY', default='django-insecure-local-placeholder')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Allow hosts can be provided as comma-separated list in env (default to vercel)
raw_allowed = config('ALLOWED_HOSTS', default='.vercel.app')
# Split, strip whitespace and remove empty entries
ALLOWED_HOSTS = [h.strip() for h in raw_allowed.split(',') if h.strip()]
# Ensure localhost loopback is allowed for local testing
if '127.0.0.1' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('127.0.0.1')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notes',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise should come directly after SecurityMiddleware to serve static files
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stunotesapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 👈 global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stunotesapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

"""
Database configuration order of precedence:
1. DATABASE_URL (useful for Supabase / single connection string)
2. Individual DB_* environment variables
3. sqlite fallback for local/testing when none provided
"""
database_url = config('DATABASE_URL', default='')
if database_url:
    # Parse DATABASE_URL using dj_database_url (already in requirements)
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }
    # Ensure SSL when using managed Postgres (Supabase usually requires it)
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    DATABASES['default']['OPTIONS'].setdefault('sslmode', 'require')
else:
    # For security purposes, read database credentials from environment variables safely.
    db_engine = config('DB_ENGINE', default='')
    if db_engine:
        # read optional port safely
        db_port_raw = config('DB_PORT', default=None)
        try:
            db_port = int(db_port_raw) if db_port_raw else ''
        except (TypeError, ValueError):
            db_port = ''

        DATABASES = {
            'default': {
                'ENGINE': db_engine,
                'HOST': config('DB_HOST', default=''),
                'NAME': config('DB_NAME', default=''),
                'USER': config('DB_USER', default=''),
                'PASSWORD': config('DB_PASSWORD', default=''),
                'PORT': db_port,
                'OPTIONS': {
                    'sslmode': 'require',
                },
                'CONN_MAX_AGE': 0,
            }
        }
    else:
        # Lightweight sqlite fallback for testing / initial deploy when no DB env vars set
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Redirect to login page if user is not authenticated
LOGIN_URL = 'notes:login'



#Configure static files for user interface and for future use ninyo
STATIC_URL = '/static/'

# This should match your actual directory structure
STATICFILES_DIRS = [
    BASE_DIR / "notes" / "static"  # Point to the inner 'notes' folder
]

# Where collected static files will go after running `collectstatic`
STATIC_ROOT = BASE_DIR / "static_cdn"

# Use WhiteNoise compressed manifest storage in production for efficient static serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'notes.User'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Internationalization for time and language nato
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'