# Generated by Django 4.2 on 2025-11-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_only',
            field=models.BooleanField(default=False, help_text='If True, this admin account cannot access user features'),
        ),
    ]
